-- MySQL Script generated by MySQL Workbench
-- Mon Jun 26 18:42:11 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `usuario_id` INT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(55) NOT NULL,
  `password` VARCHAR(32) NOT NULL,
  `nombre` VARCHAR(60) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `fecha_registro` DATE NOT NULL,
  PRIMARY KEY (`usuario_id`));


-- -----------------------------------------------------
-- Table `mydb`.`inventario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`inventario` (
  `inventario_id` INT NOT NULL AUTO_INCREMENT,
  `producto_id` INT NOT NULL,
  `centro_distrib_id` INT NOT NULL,
  `cantidad_unidades` INT NOT NULL,
  PRIMARY KEY (`inventario_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`centro_distrib`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`centro_distrib` (
  `centro_distrib_id` INT NOT NULL AUTO_INCREMENT,
  `nombre_centro` VARCHAR(45) NOT NULL,
  `ciudad_centro` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`centro_distrib_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`producto` (
  `producto_id` INT NOT NULL AUTO_INCREMENT,
  `nombre_prod` VARCHAR(45) NOT NULL,
  `tipo_producto` VARCHAR(45) NOT NULL,
  `cantidad_inventario_id` INT NOT NULL,
  `precio_producto` DECIMAL NOT NULL,
  `centrodistrib_prod` INT NOT NULL,
  PRIMARY KEY (`producto_id`),
  INDEX `inventario_prod_id_idx` (`cantidad_inventario_id` ASC) VISIBLE,
  INDEX `centrodistri_prod_id_idx` (`centrodistrib_prod` ASC) VISIBLE,
  CONSTRAINT `inventario_prod_id`
    FOREIGN KEY (`cantidad_inventario_id`)
    REFERENCES `mydb`.`inventario` (`inventario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `centrodistri_prod_id`
    FOREIGN KEY (`centrodistrib_prod`)
    REFERENCES `mydb`.`centro_distrib` (`centro_distrib_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`orden`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`orden` (
  `orden_id` INT UNSIGNED NOT NULL,
  `user_id` INT NOT NULL,
  `producto_id` INT NOT NULL,
  `cantidad_orden` INT NOT NULL,
  `precio_orden` DECIMAL NOT NULL,
  PRIMARY KEY (`orden_id`),
  INDEX `user_orden_id_idx` (`user_id` ASC) VISIBLE,
  INDEX `producto_orden_id_idx` (`producto_id` ASC) VISIBLE,
  CONSTRAINT `user_orden_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`usuario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `producto_orden_id`
    FOREIGN KEY (`producto_id`)
    REFERENCES `mydb`.`producto` (`producto_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`distribucion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`distribucion` (
  `distribucion_id` INT NOT NULL AUTO_INCREMENT,
  `centro_distribu_id` INT NOT NULL,
  `orden_distri_id` INT NOT NULL,
  PRIMARY KEY (`distribucion_id`),
  INDEX `orden_distri_id_idx` (`orden_distri_id` ASC) VISIBLE,
  INDEX `centro_distribu_id_idx` (`centro_distribu_id` ASC) VISIBLE,
  CONSTRAINT `orden_distri_id`
    FOREIGN KEY (`orden_distri_id`)
    REFERENCES `mydb`.`orden` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `centro_distribu_id`
    FOREIGN KEY (`centro_distribu_id`)
    REFERENCES `mydb`.`centro_distrib` (`centro_distrib_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
